name: Update Berita

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
  run: |
    pip install playwright
    pip install mkdocs
    pip install mkdocs-material

    playwright install chromium

      - name: Run Scraper
        run: |
          python fetch_berita.py

      - name: Upload Debug Files
        uses: actions/upload-artifact@v4
        with:
          name: debug-files
          path: |
            debug.html
            debug.txt

      - name: Commit Files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add docs

          git commit -m "update berita" || echo "No changes"

          git push

      - name: Deploy GitHub Pages
        run: |
          mkdocs gh-deploy --force
